os: linux
language: python

env:
  global:
    - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
    - SEGFAULT_SIGNALS=all
    - TOX_SKIP_MISSING_INTERPRETERS="False"

before_install:
  - python --version
  - pip --version
  - uname -a
  - lsb_release -a
  - sudo python -m pip install -U pip
  - python -m pip install tox
  - sudo apt-get install jq
  - curl -LSs "$(curl -LSs https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r '.assets | map({name, browser_download_url} | select(.name | endswith(".jar"))) | .[0].browser_download_url')" -o codacy-coverage-reporter-assembly.jar


cache: pip
script: tox -vv

jobs:
  include:
  - stage: Build_n_test
    env: TOXENV=check
  - stage: Build_n_test
    python: '3.6'
    env: TOXENV=clean,py36-cov
  - stage: Build_n_test
    python: '3.7'
    env: TOXENV=clean,py37-cov
  - stage: Build_n_test
    python: '3.8'
    env: TOXENV=clean,py38-cov

after_success:
  - tox -e codecov
  - java -jar codacy-coverage-reporter-assembly.jar report -l Python -r test-results/junit-test-results.xml

after_failure:
  - more .tox/log/* | cat
  - more .tox/*/log/* | cat

#deploy:
#  provider: script
#  script: .travis/deploy.sh
#  on:
#    all_branches: true


#notifications:
#  email:
#    on_success: never
#    on_failure: never
